version: "3"
services:
  postgresdbserver:
    image: postgres:9.6.6
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=sysml2
    ports:
      - "5432:5432"
    volumes:
      - postgresdbserver:/var/lib/postgresql/data
    networks:
      - thenetwork

  sysmlapiserver:
    build:
      context: .
      dockerfile: Dockerfile.api
    tty: true
    depends_on:
      - postgresdbserver
    ports:
      - "9000:9000"
    restart: always
    networks:
      - thenetwork

  tljh:
    build:
      context: .
      dockerfile: Dockerfile.tljh
    privileged: true
    # restart: always
    ports:
      - 8888:80
    environment:
      TZ: UTC/NEW_YORK
    volumes:
      - ./config/config.yaml:/opt/tljh/config/config.yaml
      - ./envs:/tmp/envs/
      - ./updates:/tmp/updates/
      - user-data:/home
    networks:
      - thenetwork

networks:
  thenetwork:
    external: true

volumes:
  postgresdbserver:
    external: true
  user-data: