base_url: /selab/
limits:
  memory: 8G
  cpu: 4
services:
  cull:
    enabled: false
user_environment:
  default_app: jupyterlab
  default_conda_packages:
  - numpy
  - matplotlib
  - pandas
  - scipy
  - sos
  - sos-notebook
  - jupyterlab-sos
  - sos-python
  - sos-bash
  - sos-r
  - sos-javascript
users:
  admin:
  - admin
